### ISSUE TITLE
Flaky Test: tvu::tests::test_tvu_exit_no_wen_restart

### ISSUE THREAD

**Issue by steviez** [anza-xyz/agave#3159]
#### Problem
I saw this test fail on a random CI run:
https://buildkite.com/anza/agave/builds/11961#019286d3-e00a-46b1-b4a4-38543c712c39

```
failures:

---- tvu::tests::test_tvu_exit_no_wen_restart stdout ----
thread 'solReplayStage' panicked at core/src/replay_stage.rs:2948:22:
parent of active bank must exist in progress map
thread 'tvu::tests::test_tvu_exit_no_wen_restart' panicked at core/src/tvu.rs:556:20:
called `Result::unwrap()` on an `Err` value: Any { .. }

failures:
    tvu::tests::test_tvu_exit_no_wen_restart
```

#### Proposed Solution
Debug

**Comment by steviez** [comment]
Test was removed in https://github.com/anza-xyz/agave/pull/10493 so nothing else to do here
