### ISSUE TITLE
How do I use an HTTP proxy while running a Solana validator? #35505

### ISSUE THREAD

**Issue by jin10086** [anza-xyz/agave#678]
My local server cannot directly access the internet and needs a proxy setup. However,
when I directly export the HTTP proxy using export http_proxy="127.0.0.1:8118" and then run Solana validator, it doesn't work.

i use 
```
proxychains4 solana-validator \
    --identity /mnt/sdb1/node/sol/validator-keypair.json \
    --no-voting \
    --no-port-check \
    --restricted-repair-only-mode \
    --rpc-port 8899 \
    --dynamic-port-range 9000-9100 \
    --full-rpc-api \
    --gossip-host 127.0.0.1 \
    --no-os-network-stats-reporting \
    --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --ledger /mnt/sdb1/node/sol/snap1 \
    --private-rpc \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size \
```

the error
```
solana_validator::bootstrap] Failed to get RPC nodes: Unable to find any RPC peers. Consider checking system clock, removing `--no-port-check`, or adjusting `--known-validator ...` arguments as applicable
```

and remove no-port-check

error 
```
[2024-04-09T14:38:18.274870491Z INFO  solana_perf::perf_libs] perf-libs found at "/root/.local/share/solana/install/releases/1.17.29/solana-release/bin/perf-libs"
[2024-04-09T14:38:18.274884031Z INFO  solana_perf::perf_libs] setting ld_library_path to: "/root/.local/share/solana/install/releases/1.17.29/solana-release/bin/perf-libs:/root/.gvm/pkgsets/go1.21/global/overlay/lib:/root/.gvm/pkgsets/go1.21/global/overlay/lib:/root/.gvm/pkgsets/go1.21/global/overlay/lib"
thread 'main' panicked at validator/src/bootstrap.rs:128:38:
called `Result::unwrap()` on an `Err` value: MulticastIpAddr(224.0.0.3)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: solana_validator::bootstrap::rpc_bootstrap
   4: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2024-04-09T14:38:18.294977513Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at validator/src/bootstrap.rs:128:38:
    called `Result::unwrap()` on an `Err` value: MulticastIpAddr(224.0.0.3)" location="validator/src/bootstrap.rs:128:38" version="1.17.29 (src:d18cbc80; feat:3746964731, client:SolanaLabs)"
```

**Comment by CriesofCarrots** [comment]
We don't offer technical support via github issues. You can try #validator-beginners on [Discord](https://solana.com/discord)
